### ISSUE TITLE
Start/Stop all mocker instances buttons

### ISSUE THREAD

**Issue by MihneaNandra** [eshengsky/axios-mocker#2]
You should create a button for starting and stopping all instances for mocking data at once. 
It is very inconvenient to start or stop mocking instances one by one. This becomes very cumbersome for large number of instances.

**Comment by eshengsky** [comment]
Good idea, I will implement this when I have time.

**Comment by eshengsky** [comment]
Click axios-mocker extension button (looks like `M`) in extension bar, in the popup window there's a toggle button, that's it.
